image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 14 x64
  - yarn

artifacts:
  - path: dist_electron 
    name: test logs
    type: zip

  - path: 'dist_electron\read-chinese Setup 0.1.0.exe'
    name: Install Program

build_script:
  - yarn electron:build 

test: off

