// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GenerateImage(arg1:string):Promise<backend.ImageInfo>;

export function GenerateSentences(arg1:string):Promise<Array<string>>;
