// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateImage(arg1) {
  return window['go']['backend']['aiGenerator']['GenerateImage'](arg1);
}

export function GenerateSentences(arg1) {
  return window['go']['backend']['aiGenerator']['GenerateSentences'](arg1);
}
