// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateAnkiNote(arg1:backend.Fields,arg2:Array<string>):Promise<string>;

export function GetAnkiNote(arg1:string):Promise<backend.RawAnkiNote>;

export function GetAnkiNoteSkeleton(arg1:string):Promise<backend.RawAnkiNote>;

export function ImportAnkiKeywords():Promise<Error>;

export function UpdateNoteFields(arg1:number,arg2:backend.Fields):Promise<string>;
