// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateAnkiCard(arg1:backend.Fields,arg2:Array<string>):Promise<string>;

export function GetAnkiNoteSkeleton(arg1:string):Promise<backend.RawAnkiNote>;
