// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAnkiNote(arg1, arg2) {
  return window['go']['backend']['ankiInterface']['CreateAnkiNote'](arg1, arg2);
}

export function GetAnkiNote(arg1) {
  return window['go']['backend']['ankiInterface']['GetAnkiNote'](arg1);
}

export function GetAnkiNoteSkeleton(arg1) {
  return window['go']['backend']['ankiInterface']['GetAnkiNoteSkeleton'](arg1);
}

export function ImportAnkiKeywords() {
  return window['go']['backend']['ankiInterface']['ImportAnkiKeywords']();
}

export function LoadProblemCards() {
  return window['go']['backend']['ankiInterface']['LoadProblemCards']();
}

export function UpdateNoteFields(arg1, arg2) {
  return window['go']['backend']['ankiInterface']['UpdateNoteFields'](arg1, arg2);
}
