// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAnkiNote(arg1, arg2) {
  return window['go']['backend']['AnkiInterface']['CreateAnkiNote'](arg1, arg2);
}

export function GetAnkiNote(arg1) {
  return window['go']['backend']['AnkiInterface']['GetAnkiNote'](arg1);
}

export function GetAnkiNoteSkeleton(arg1) {
  return window['go']['backend']['AnkiInterface']['GetAnkiNoteSkeleton'](arg1);
}

export function UpdateNoteFields(arg1, arg2) {
  return window['go']['backend']['AnkiInterface']['UpdateNoteFields'](arg1, arg2);
}
