// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigurationCheck() {
  return window['go']['backend']['ankiInterface']['ConfigurationCheck']();
}

export function CreateAnkiNote(arg1, arg2) {
  return window['go']['backend']['ankiInterface']['CreateAnkiNote'](arg1, arg2);
}

export function GetAnkiNote(arg1) {
  return window['go']['backend']['ankiInterface']['GetAnkiNote'](arg1);
}

export function HealthCheck() {
  return window['go']['backend']['ankiInterface']['HealthCheck']();
}

export function ImportAnkiKeywords() {
  return window['go']['backend']['ankiInterface']['ImportAnkiKeywords']();
}

export function LoadDecks() {
  return window['go']['backend']['ankiInterface']['LoadDecks']();
}

export function LoadModelFields(arg1) {
  return window['go']['backend']['ankiInterface']['LoadModelFields'](arg1);
}

export function LoadModels() {
  return window['go']['backend']['ankiInterface']['LoadModels']();
}

export function LoadProblemCards(arg1) {
  return window['go']['backend']['ankiInterface']['LoadProblemCards'](arg1);
}

export function LoadTemplate() {
  return window['go']['backend']['ankiInterface']['LoadTemplate']();
}

export function UpdateNoteFields(arg1, arg2) {
  return window['go']['backend']['ankiInterface']['UpdateNoteFields'](arg1, arg2);
}

export function UpdatePinyin(arg1) {
  return window['go']['backend']['ankiInterface']['UpdatePinyin'](arg1);
}

export function UpdateSentenceAudio(arg1) {
  return window['go']['backend']['ankiInterface']['UpdateSentenceAudio'](arg1);
}

export function UpdateWordAudio(arg1) {
  return window['go']['backend']['ankiInterface']['UpdateWordAudio'](arg1);
}
