// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAnkiCard(arg1, arg2) {
  return window['go']['backend']['AnkiInterface']['CreateAnkiCard'](arg1, arg2);
}

export function GetAnkiNoteSkeleton(arg1) {
  return window['go']['backend']['AnkiInterface']['GetAnkiNoteSkeleton'](arg1);
}
