// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilePicker(arg1:string):Promise<string>;

export function GetFileName(arg1:string):Promise<string>;

export function HealthCheck():Promise<void>;

export function SaveFile():Promise<string>;
