// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilePicker(arg1) {
  return window['go']['backend']['Backend']['FilePicker'](arg1);
}

export function GetFileName(arg1) {
  return window['go']['backend']['Backend']['GetFileName'](arg1);
}

export function HealthCheck() {
  return window['go']['backend']['Backend']['HealthCheck']();
}

export function SaveFile() {
  return window['go']['backend']['Backend']['SaveFile']();
}
