// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBook(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['bookLibrary']['AddBook'](arg1, arg2, arg3, arg4);
}

export function BookExists(arg1, arg2) {
  return window['go']['backend']['bookLibrary']['BookExists'](arg1, arg2);
}

export function BookPathsPortable() {
  return window['go']['backend']['bookLibrary']['BookPathsPortable']();
}

export function DeleteBook(arg1) {
  return window['go']['backend']['bookLibrary']['DeleteBook'](arg1);
}

export function ExportDetailedBooks(arg1) {
  return window['go']['backend']['bookLibrary']['ExportDetailedBooks'](arg1);
}

export function FixBookPaths() {
  return window['go']['backend']['bookLibrary']['FixBookPaths']();
}

export function GetBook(arg1) {
  return window['go']['backend']['bookLibrary']['GetBook'](arg1);
}

export function GetBookFrequencies(arg1) {
  return window['go']['backend']['bookLibrary']['GetBookFrequencies'](arg1);
}

export function GetBookGraph(arg1) {
  return window['go']['backend']['bookLibrary']['GetBookGraph'](arg1);
}

export function GetBooks(arg1) {
  return window['go']['backend']['bookLibrary']['GetBooks'](arg1);
}

export function GetDetailedBooks() {
  return window['go']['backend']['bookLibrary']['GetDetailedBooks']();
}

export function GetFavoriteFrequencies() {
  return window['go']['backend']['bookLibrary']['GetFavoriteFrequencies']();
}

export function HealthCheck() {
  return window['go']['backend']['bookLibrary']['HealthCheck']();
}

export function LearningTarget() {
  return window['go']['backend']['bookLibrary']['LearningTarget']();
}

export function LearningTargetBook(arg1) {
  return window['go']['backend']['bookLibrary']['LearningTargetBook'](arg1);
}

export function LearningTargetFavorites() {
  return window['go']['backend']['bookLibrary']['LearningTargetFavorites']();
}

export function RecalculateBooks() {
  return window['go']['backend']['bookLibrary']['RecalculateBooks']();
}

export function SetFavorite(arg1, arg2) {
  return window['go']['backend']['bookLibrary']['SetFavorite'](arg1, arg2);
}

export function SetRead(arg1, arg2) {
  return window['go']['backend']['bookLibrary']['SetRead'](arg1, arg2);
}

export function TotalRead() {
  return window['go']['backend']['bookLibrary']['TotalRead']();
}

export function TotalReadChars() {
  return window['go']['backend']['bookLibrary']['TotalReadChars']();
}
