// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBook(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['BookLibrary']['AddBook'](arg1, arg2, arg3, arg4);
}

export function BookExists(arg1, arg2) {
  return window['go']['backend']['BookLibrary']['BookExists'](arg1, arg2);
}

export function DeleteBook(arg1) {
  return window['go']['backend']['BookLibrary']['DeleteBook'](arg1);
}

export function GetBook(arg1) {
  return window['go']['backend']['BookLibrary']['GetBook'](arg1);
}

export function GetBooks() {
  return window['go']['backend']['BookLibrary']['GetBooks']();
}

export function GetSomeBooks(arg1) {
  return window['go']['backend']['BookLibrary']['GetSomeBooks'](arg1);
}

export function LearningTarget() {
  return window['go']['backend']['BookLibrary']['LearningTarget']();
}

export function LearningTargetBook(arg1) {
  return window['go']['backend']['BookLibrary']['LearningTargetBook'](arg1);
}

export function SetFavorite(arg1, arg2) {
  return window['go']['backend']['BookLibrary']['SetFavorite'](arg1, arg2);
}

export function SetRead(arg1, arg2) {
  return window['go']['backend']['BookLibrary']['SetRead'](arg1, arg2);
}

export function TopUnknownWords(arg1, arg2) {
  return window['go']['backend']['BookLibrary']['TopUnknownWords'](arg1, arg2);
}

export function TotalRead() {
  return window['go']['backend']['BookLibrary']['TotalRead']();
}
