// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBook(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['bookLibrary']['AddBook'](arg1, arg2, arg3, arg4);
}

export function BookExists(arg1, arg2) {
  return window['go']['backend']['bookLibrary']['BookExists'](arg1, arg2);
}

export function DeleteBook(arg1) {
  return window['go']['backend']['bookLibrary']['DeleteBook'](arg1);
}

export function GetBook(arg1) {
  return window['go']['backend']['bookLibrary']['GetBook'](arg1);
}

export function GetBooks() {
  return window['go']['backend']['bookLibrary']['GetBooks']();
}

export function GetDetailedBooks(arg1) {
  return window['go']['backend']['bookLibrary']['GetDetailedBooks'](arg1);
}

export function GetSomeBooks(arg1) {
  return window['go']['backend']['bookLibrary']['GetSomeBooks'](arg1);
}

export function HealthCheck() {
  return window['go']['backend']['bookLibrary']['HealthCheck']();
}

export function LearningTarget() {
  return window['go']['backend']['bookLibrary']['LearningTarget']();
}

export function LearningTargetBook(arg1) {
  return window['go']['backend']['bookLibrary']['LearningTargetBook'](arg1);
}

export function LearningTargetFavorites() {
  return window['go']['backend']['bookLibrary']['LearningTargetFavorites']();
}

export function RecalculateBooks() {
  return window['go']['backend']['bookLibrary']['RecalculateBooks']();
}

export function SetFavorite(arg1, arg2) {
  return window['go']['backend']['bookLibrary']['SetFavorite'](arg1, arg2);
}

export function SetRead(arg1, arg2) {
  return window['go']['backend']['bookLibrary']['SetRead'](arg1, arg2);
}

export function TopUnknownWords(arg1, arg2) {
  return window['go']['backend']['bookLibrary']['TopUnknownWords'](arg1, arg2);
}

export function TotalRead() {
  return window['go']['backend']['bookLibrary']['TotalRead']();
}

export function TotalReadChars() {
  return window['go']['backend']['bookLibrary']['TotalReadChars']();
}
