// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBooks(arg1) {
  return window['go']['backend']['BookLibrary']['GetBooks'](arg1);
}

export function LearningTarget() {
  return window['go']['backend']['BookLibrary']['LearningTarget']();
}
