// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCalibreBooks() {
  return window['go']['backend']['Calibre']['GetCalibreBooks']();
}

export function ImportCalibreBooks(arg1) {
  return window['go']['backend']['Calibre']['ImportCalibreBooks'](arg1);
}
