// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetCalibreBooks():Promise<Array<backend.CalibreBook>>;

export function ImportCalibreBooks(arg1:Array<backend.CalibreBook>):Promise<Error>;
