// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigDir() {
  return window['go']['backend']['ConfigExposer']['GetConfigDir']();
}

export function ZipConfigDir() {
  return window['go']['backend']['ConfigExposer']['ZipConfigDir']();
}
