// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddCedict():Promise<void>;

export function AddMigakuDictionary(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteDictionary(arg1:string):Promise<void>;

export function ExportDictionaryInfo():Promise<backend.DictionaryInfo>;

export function GetDefinitions(arg1:Array<string>):Promise<backend.WordDefinitions>;

export function GetDefinitionsForWord(arg1:string,arg2:string):Promise<Array<backend.DictionaryDefinition>>;

export function GetDictionaryInfo():Promise<backend.DictionaryInfoMap>;

export function GetPossibleWords(arg1:string):Promise<Array<string>>;

export function HealthCheck():Promise<string>;

export function IsInDictionary(arg1:string):Promise<boolean>;

export function PassSegmentation(arg1:backend.Segmentation):Promise<void>;

export function SetPrimaryDict(arg1:string):Promise<void>;
