// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddDictionary(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteDictionary(arg1:string):Promise<void>;

export function GetDefinitions(arg1:Array<backend.UnknownWordEntry>):Promise<Array<backend.UnknownWordEntry>>;

export function GetDefinitionsForWord(arg1:string,arg2:string):Promise<Array<backend.DictionaryEntry>>;

export function GetDictionaryInfo():Promise<backend.DictionaryInfoMap>;

export function GetPossibleWords(arg1:string):Promise<Array<backend.UnknownWordEntry>>;

export function SetPrimaryDict(arg1:string):Promise<void>;
