// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCedict() {
  return window['go']['backend']['Dictionaries']['AddCedict']();
}

export function AddMigakuDictionary(arg1, arg2, arg3) {
  return window['go']['backend']['Dictionaries']['AddMigakuDictionary'](arg1, arg2, arg3);
}

export function DeleteDictionary(arg1) {
  return window['go']['backend']['Dictionaries']['DeleteDictionary'](arg1);
}

export function GetDefinitions(arg1) {
  return window['go']['backend']['Dictionaries']['GetDefinitions'](arg1);
}

export function GetDefinitionsForWord(arg1, arg2) {
  return window['go']['backend']['Dictionaries']['GetDefinitionsForWord'](arg1, arg2);
}

export function GetDictionaryInfo() {
  return window['go']['backend']['Dictionaries']['GetDictionaryInfo']();
}

export function GetPossibleWords(arg1) {
  return window['go']['backend']['Dictionaries']['GetPossibleWords'](arg1);
}

export function HealthCheck() {
  return window['go']['backend']['Dictionaries']['HealthCheck']();
}

export function IsInDictionary(arg1) {
  return window['go']['backend']['Dictionaries']['IsInDictionary'](arg1);
}

export function SetPrimaryDict(arg1) {
  return window['go']['backend']['Dictionaries']['SetPrimaryDict'](arg1);
}
