// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GenerateSentenceTable():Promise<Error>;

export function GenerateSentenceTableForBook(arg1:backend.Book):Promise<number>;

export function GetSentencesForWord(arg1:string,arg2:Array<number>):Promise<Array<string>>;

export function UpdateSentenceTable(arg1:string):Promise<Error>;
