// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSentencesForWord(arg1:string,arg2:Array<number>):Promise<Array<string>>;
