// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchBookCovers(arg1, arg2) {
  return window['go']['backend']['ImageClient']['SearchBookCovers'](arg1, arg2);
}

export function SearchImages(arg1) {
  return window['go']['backend']['ImageClient']['SearchImages'](arg1);
}
