// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWord(arg1, arg2) {
  return window['go']['backend']['knownWords']['AddWord'](arg1, arg2);
}

export function AddWords(arg1) {
  return window['go']['backend']['knownWords']['AddWords'](arg1);
}

export function DeleteWord(arg1) {
  return window['go']['backend']['knownWords']['DeleteWord'](arg1);
}

export function GetOccurances(arg1) {
  return window['go']['backend']['knownWords']['GetOccurances'](arg1);
}

export function GetStatsInfo() {
  return window['go']['backend']['knownWords']['GetStatsInfo']();
}

export function GetUnknownHskWords(arg1, arg2) {
  return window['go']['backend']['knownWords']['GetUnknownHskWords'](arg1, arg2);
}

export function GetWordStats() {
  return window['go']['backend']['knownWords']['GetWordStats']();
}

export function GetWords() {
  return window['go']['backend']['knownWords']['GetWords']();
}

export function GetWordsGrid() {
  return window['go']['backend']['knownWords']['GetWordsGrid']();
}

export function ImportCSVWords(arg1) {
  return window['go']['backend']['knownWords']['ImportCSVWords'](arg1);
}

export function IsKnown(arg1) {
  return window['go']['backend']['knownWords']['IsKnown'](arg1);
}

export function IsKnownChar(arg1) {
  return window['go']['backend']['knownWords']['IsKnownChar'](arg1);
}

export function IsWellKnown(arg1) {
  return window['go']['backend']['knownWords']['IsWellKnown'](arg1);
}

export function SyncFrequency() {
  return window['go']['backend']['knownWords']['SyncFrequency']();
}
