// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetWordStats():Promise<backend.WordStats>;

export function GetWords():Promise<{[key: string]: number}>;
