// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddWord(arg1:string,arg2:number):Promise<Error>;

export function AddWords(arg1:Array<backend.WordEntry>):Promise<Error>;

export function DeleteWord(arg1:string):Promise<Error>;

export function GetOccurances(arg1:Array<string>):Promise<{[key: string]: number}>;

export function GetStatsInfo():Promise<Array<backend.TimeQuery>>;

export function GetUnknownHskWords(arg1:string,arg2:number):Promise<Array<string>>;

export function GetWordStats():Promise<backend.WordStats>;

export function GetWords():Promise<backend.Words>;

export function GetWordsGrid():Promise<Array<backend.WordGridRow>>;

export function ImportCSVWords(arg1:string):Promise<Error>;

export function IsKnown(arg1:string):Promise<boolean>;

export function IsKnownChar(arg1:number):Promise<boolean>;

export function IsWellKnown(arg1:string):Promise<boolean>;

export function SyncFrequency():Promise<void>;
