// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWordStats() {
  return window['go']['backend']['KnownWords']['GetWordStats']();
}

export function GetWords() {
  return window['go']['backend']['KnownWords']['GetWords']();
}
