// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddWord(arg1:string,arg2:number):Promise<void>;

export function GetWordStats():Promise<backend.WordStats>;
