// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ExportVoice():Promise<backend.TTSVoice>;

export function GetVoices():Promise<Array<backend.TTSVoice>>;

export function Synthesize(arg1:string):Promise<string>;
