// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportVoice() {
  return window['go']['backend']['TextToSpeech']['ExportVoice']();
}

export function GetVoices() {
  return window['go']['backend']['TextToSpeech']['GetVoices']();
}

export function Synthesize(arg1) {
  return window['go']['backend']['TextToSpeech']['Synthesize'](arg1);
}
