// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGroupSettings(arg1) {
  return window['go']['backend']['UserSettings']['GetGroupSettings'](arg1);
}

export function GetOptionValue(arg1) {
  return window['go']['backend']['UserSettings']['GetOptionValue'](arg1);
}
