// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDict(arg1) {
  return window['go']['backend']['UserConfig']['DeleteDict'](arg1);
}

export function DeleteMapping(arg1) {
  return window['go']['backend']['UserConfig']['DeleteMapping'](arg1);
}

export function ExportMapping() {
  return window['go']['backend']['UserConfig']['ExportMapping']();
}

export function GetMapping(arg1) {
  return window['go']['backend']['UserConfig']['GetMapping'](arg1);
}

export function GetTimesRan() {
  return window['go']['backend']['UserConfig']['GetTimesRan']();
}

export function GetUserSettings() {
  return window['go']['backend']['UserConfig']['GetUserSettings']();
}

export function SaveDict(arg1, arg2, arg3) {
  return window['go']['backend']['UserConfig']['SaveDict'](arg1, arg2, arg3);
}

export function SetMapping(arg1, arg2) {
  return window['go']['backend']['UserConfig']['SetMapping'](arg1, arg2);
}

export function SetPrimaryDict(arg1) {
  return window['go']['backend']['UserConfig']['SetPrimaryDict'](arg1);
}

export function SetUserSetting(arg1, arg2) {
  return window['go']['backend']['UserConfig']['SetUserSetting'](arg1, arg2);
}

export function SetUserSettingBool(arg1, arg2) {
  return window['go']['backend']['UserConfig']['SetUserSettingBool'](arg1, arg2);
}

export function SetUserSettingInt(arg1, arg2) {
  return window['go']['backend']['UserConfig']['SetUserSettingInt'](arg1, arg2);
}

export function UpdateTimesRan() {
  return window['go']['backend']['UserConfig']['UpdateTimesRan']();
}
