// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserSetting(arg1) {
  return window['go']['backend']['UserSettings']['GetUserSetting'](arg1);
}

export function GetUserSettingBool(arg1) {
  return window['go']['backend']['UserSettings']['GetUserSettingBool'](arg1);
}

export function GetUserSettingInt(arg1) {
  return window['go']['backend']['UserSettings']['GetUserSettingInt'](arg1);
}

export function SetUserSetting(arg1, arg2) {
  return window['go']['backend']['UserSettings']['SetUserSetting'](arg1, arg2);
}

export function SetUserSettingBool(arg1, arg2) {
  return window['go']['backend']['UserSettings']['SetUserSettingBool'](arg1, arg2);
}

export function SetUserSettingInt(arg1, arg2) {
  return window['go']['backend']['UserSettings']['SetUserSettingInt'](arg1, arg2);
}
