// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function DeleteDict(arg1:string):Promise<void>;

export function ExportMapping():Promise<backend.FieldsMapping>;

export function GetTimesRan():Promise<number>;

export function GetUserSetting(arg1:string):Promise<string>;

export function GetUserSettingBool(arg1:string):Promise<boolean>;

export function GetUserSettingInt(arg1:string):Promise<number>;

export function SaveDict(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetPrimaryDict(arg1:string):Promise<void>;

export function SetUserSetting(arg1:string,arg2:string):Promise<void>;

export function SetUserSettingBool(arg1:string,arg2:boolean):Promise<void>;

export function SetUserSettingInt(arg1:string,arg2:number):Promise<void>;

export function UpdateTimesRan():Promise<void>;
