// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetGroupSettings(arg1:string):Promise<Array<backend.UserSetting>>;

export function GetOptionValue(arg1:string):Promise<string>;
