// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddList(arg1:string,arg2:string):Promise<void>;

export function DeleteList(arg1:string):Promise<void>;

export function ExportUnknownWordRow():Promise<backend.UnknownWordRow>;

export function ExportWordListInfo():Promise<backend.WordListInfo>;

export function GetFrequencyList(arg1:string):Promise<{[key: string]: number}>;

export function GetLists():Promise<Array<string>>;

export function GetPrimaryList():Promise<string>;

export function GetUnknownHskWords(arg1:string,arg2:number):Promise<Array<string>>;

export function GetUnknownListWords(arg1:string):Promise<Array<string>>;

export function GetWordData(arg1:Array<string>,arg2:string,arg3:string):Promise<Array<backend.UnknownWordRow>>;

export function GetWordListsInfo():Promise<{[key: string]: backend.WordListInfo}>;

export function SetPrimaryList(arg1:string):Promise<void>;
