// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddList(arg1, arg2) {
  return window['go']['backend']['wordLists']['AddList'](arg1, arg2);
}

export function DeleteList(arg1) {
  return window['go']['backend']['wordLists']['DeleteList'](arg1);
}

export function ExportUnknownWordRow() {
  return window['go']['backend']['wordLists']['ExportUnknownWordRow']();
}

export function ExportWordListInfo() {
  return window['go']['backend']['wordLists']['ExportWordListInfo']();
}

export function GetFrequencyList(arg1) {
  return window['go']['backend']['wordLists']['GetFrequencyList'](arg1);
}

export function GetLists() {
  return window['go']['backend']['wordLists']['GetLists']();
}

export function GetPrimaryList() {
  return window['go']['backend']['wordLists']['GetPrimaryList']();
}

export function GetUnknownHskWords(arg1, arg2) {
  return window['go']['backend']['wordLists']['GetUnknownHskWords'](arg1, arg2);
}

export function GetUnknownListWords(arg1) {
  return window['go']['backend']['wordLists']['GetUnknownListWords'](arg1);
}

export function GetWordData(arg1, arg2, arg3) {
  return window['go']['backend']['wordLists']['GetWordData'](arg1, arg2, arg3);
}

export function GetWordListsInfo() {
  return window['go']['backend']['wordLists']['GetWordListsInfo']();
}

export function SetPrimaryList(arg1) {
  return window['go']['backend']['wordLists']['SetPrimaryList'](arg1);
}
