// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddList(arg1, arg2) {
  return window['go']['backend']['wordLists']['AddList'](arg1, arg2);
}

export function DeleteList(arg1) {
  return window['go']['backend']['wordLists']['DeleteList'](arg1);
}

export function Destroy() {
  return window['go']['backend']['wordLists']['Destroy']();
}

export function ExportUnknownWordRow() {
  return window['go']['backend']['wordLists']['ExportUnknownWordRow']();
}

export function ExportWordListInfo() {
  return window['go']['backend']['wordLists']['ExportWordListInfo']();
}

export function GetFrequencyList(arg1) {
  return window['go']['backend']['wordLists']['GetFrequencyList'](arg1);
}

export function GetLists() {
  return window['go']['backend']['wordLists']['GetLists']();
}

export function GetPrimaryList() {
  return window['go']['backend']['wordLists']['GetPrimaryList']();
}

export function GetRows(arg1, arg2) {
  return window['go']['backend']['wordLists']['GetRows'](arg1, arg2);
}

export function GetWordListsInfo() {
  return window['go']['backend']['wordLists']['GetWordListsInfo']();
}

export function RowCount() {
  return window['go']['backend']['wordLists']['RowCount']();
}

export function SetFrequencySource(arg1) {
  return window['go']['backend']['wordLists']['SetFrequencySource'](arg1);
}

export function SetOccuranceSource(arg1) {
  return window['go']['backend']['wordLists']['SetOccuranceSource'](arg1);
}

export function SetPrimaryList(arg1) {
  return window['go']['backend']['wordLists']['SetPrimaryList'](arg1);
}

export function SetWordSourceFromAll() {
  return window['go']['backend']['wordLists']['SetWordSourceFromAll']();
}

export function SetWordSourceFromBook(arg1) {
  return window['go']['backend']['wordLists']['SetWordSourceFromBook'](arg1);
}

export function SetWordSourceFromFavorites() {
  return window['go']['backend']['wordLists']['SetWordSourceFromFavorites']();
}

export function SetWordSourceFromHsk(arg1, arg2) {
  return window['go']['backend']['wordLists']['SetWordSourceFromHsk'](arg1, arg2);
}

export function SetWordSourceFromList(arg1) {
  return window['go']['backend']['wordLists']['SetWordSourceFromList'](arg1);
}

export function SetWordSourceFromSearch(arg1) {
  return window['go']['backend']['wordLists']['SetWordSourceFromSearch'](arg1);
}

export function SortByFrequency() {
  return window['go']['backend']['wordLists']['SortByFrequency']();
}

export function SortByOccurance() {
  return window['go']['backend']['wordLists']['SortByOccurance']();
}

export function SortWordData() {
  return window['go']['backend']['wordLists']['SortWordData']();
}
