ALTER TABLE "books" ADD COLUMN "totalwords" INTEGER DEFAULT 0;
ALTER TABLE "books" ADD COLUMN "uniquewords" INTEGER DEFAULT 0;
ALTER TABLE "books" ADD COLUMN "totalcharacters" INTEGER DEFAULT 0;
ALTER TABLE "books" ADD COLUMN "uniquecharacters" INTEGER DEFAULT 0;

