// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilePicker(arg1) {
  return window['go']['main']['App']['FilePicker'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NodeIpc(arg1, arg2) {
  return window['go']['main']['App']['NodeIpc'](arg1, arg2);
}
