name: Release
on: [push]
# push:
#    tags: [ 'v*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - run: sudo apt-get update && sudo apt-get upgrade
      - run: sudo apt-get install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev
      - run: make build
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Version ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/github.com/qaware/dev-tool-kit-linux-amd64
          asset_name: dev-tool-kit-linux-amd64
          asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/github.com/qaware/dev-tool-kit-windows-amd64.exe
          asset_name: dev-tool-kit-windows-amd64.exe
          asset_content_type: application/octet-stream
#      - uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: build/github.com/qaware/dev-tool-kit-darwin-amd64
#          asset_name: dev-tool-kit-darwin-amd64
#          asset_content_type: application/octet-stream
